services:
  redis:
    image: redis:alpine3.22
    container_name: f1telemetry-redis
    ports:
      - "6379:6379"
    environment:
      # Explicitly pass the host variable value into the container's environment
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
